config/routes.rb
Rails.application.routes.draw do
  resources :cartoons
  root 'pages#index'
  match '*path', to: 'pages#index', via: :all
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cartoon.rb
class Cartoon < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cartoons_controller.rb
class CartoonsController < ApplicationController
  before_action :set_cartoon, only: [:show, :edit, :update, :destroy]

  # GET /cartoons
  # GET /cartoons.json
  def index
    @cartoons = Cartoon.all
  end

  # GET /cartoons/1
  # GET /cartoons/1.json
  def show
  end

  # GET /cartoons/new
  def new
    @cartoon = Cartoon.new
  end

  # GET /cartoons/1/edit
  def edit
  end

  # POST /cartoons
  # POST /cartoons.json
  def create
    @cartoon = Cartoon.new(cartoon_params)

    respond_to do |format|
      if @cartoon.save
        format.html { redirect_to @cartoon, notice: 'Cartoon was successfully created.' }
        format.json { render :show, status: :created, location: @cartoon }
      else
        format.html { render :new }
        format.json { render json: @cartoon.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cartoons/1
  # PATCH/PUT /cartoons/1.json
  def update
    respond_to do |format|
      if @cartoon.update(cartoon_params)
        format.html { redirect_to @cartoon, notice: 'Cartoon was successfully updated.' }
        format.json { render :show, status: :ok, location: @cartoon }
      else
        format.html { render :edit }
        format.json { render json: @cartoon.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cartoons/1
  # DELETE /cartoons/1.json
  def destroy
    @cartoon.destroy
    respond_to do |format|
      format.html { redirect_to cartoons_url, notice: 'Cartoon was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cartoon
      @cartoon = Cartoon.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cartoon_params
      params.require(:cartoon).permit(:title, :releaseyear, :country, :network, :studio, :endyear, :summary, :image)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cartoons_helper.rb
module CartoonsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/cartoons/_form.html.erb
<%= form_with(model: cartoon, local: true) do |form| %>
  <% if cartoon.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cartoon.errors.count, "error") %> prohibited this cartoon from being saved:</h2>

      <ul>
      <% cartoon.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :releaseyear %>
    <%= form.number_field :releaseyear %>
  </div>

  <div class="field">
    <%= form.label :country %>
    <%= form.text_field :country %>
  </div>

  <div class="field">
    <%= form.label :network %>
    <%= form.text_field :network %>
  </div>

  <div class="field">
    <%= form.label :studio %>
    <%= form.text_field :studio %>
  </div>

  <div class="field">
    <%= form.label :endyear %>
    <%= form.number_field :endyear %>
  </div>

  <div class="field">
    <%= form.label :summary %>
    <%= form.text_area :summary %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.text_field :image %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/cartoons/edit.html.erb
<h1>Editing Cartoon</h1>

<%= render 'form', cartoon: @cartoon %>

<%= link_to 'Show', @cartoon %> |
<%= link_to 'Back', cartoons_path %>

app/views/cartoons/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Cartoons</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Releaseyear</th>
      <th>Country</th>
      <th>Network</th>
      <th>Studio</th>
      <th>Endyear</th>
      <th>Summary</th>
      <th>Image</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cartoons.each do |cartoon| %>
      <tr>
        <td><%= cartoon.title %></td>
        <td><%= cartoon.releaseyear %></td>
        <td><%= cartoon.country %></td>
        <td><%= cartoon.network %></td>
        <td><%= cartoon.studio %></td>
        <td><%= cartoon.endyear %></td>
        <td><%= cartoon.summary %></td>
        <td><%= cartoon.image %></td>
        <td><%= link_to 'Show', cartoon %></td>
        <td><%= link_to 'Edit', edit_cartoon_path(cartoon) %></td>
        <td><%= link_to 'Destroy', cartoon, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cartoon', new_cartoon_path %>

app/views/cartoons/new.html.erb
<h1>New Cartoon</h1>

<%= render 'form', cartoon: @cartoon %>

<%= link_to 'Back', cartoons_path %>

app/views/cartoons/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @cartoon.title %>
</p>

<p>
  <strong>Releaseyear:</strong>
  <%= @cartoon.releaseyear %>
</p>

<p>
  <strong>Country:</strong>
  <%= @cartoon.country %>
</p>

<p>
  <strong>Network:</strong>
  <%= @cartoon.network %>
</p>

<p>
  <strong>Studio:</strong>
  <%= @cartoon.studio %>
</p>

<p>
  <strong>Endyear:</strong>
  <%= @cartoon.endyear %>
</p>

<p>
  <strong>Summary:</strong>
  <%= @cartoon.summary %>
</p>

<p>
  <strong>Image:</strong>
  <%= @cartoon.image %>
</p>

<%= link_to 'Edit', edit_cartoon_path(@cartoon) %> |
<%= link_to 'Back', cartoons_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WhiteBlake</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/index.html.erb
<%= javascript_pack_tag 'index' %>